### PR TITLE
Modal dialogs example

### PR DESCRIPTION
**Pull request by mikehedman**
This is a bundling of the functionality used in https://andyou.talky.io/ to display modal dialogs.

### CODE REVIEW

**Comment by fyockm** [comment]
Thanks @mikehedman - you've been busy. Will review soon.

**Comment by fyockm** [comment]
@mikehedman the modal example looks great and tests well. However, I'd like to start paring down some of these examples. I would really prefer to not have the sample ampersand app unless absolutely necessary. You could probably drop the whole "collection demo" part of this and keep the same relevance.

If you disagree or don't have time to update, please let me know.

**Comment by fyockm** [comment]
@mikehedman decided to save you the effort and just go ahead and prune. Again, please let me know if something important was removed. Thanks!

**Comment by mikehedman** [comment]
@fyockm thanks for the clean out and the pull.  There are two sides to the coin. First, I like things "clean" and as little "magic" as possible. So I did a fair bit of simplifying in the Hoodie example. On the other hand, I think there's a pedagogical argument for having a canonical base (the stock Ampersand app), and then doing a clean insertion of the new technology. That way, there are fewer moving parts, and the new technique stands out clearly - as I said in the readme file: just look at these two commits to see how to do it.
But, I agree with simple is better.  And I like your middle ground - a context that people are familiar with (the amp app), but rip out the bits that are just background noise to the technique being demoed.
Again, thanks!

**Pull request merged**
